### ISSUE TITLE
You have access to the Concrete5 API for the site named Array.?

### ISSUE THREAD

**Issue by nmohanan** [olsgreen/slim-concrete5#2]
I have tried your extension for concrete5 integration, i have installed this on my route folder(www/test) and the same folder i kept concrete5(www/test), and changed the DIR_BASE settings in Concrete5.php file, and i checked the url, it is showing the slim but not giving the $siteName.$authString, also commented the Concrete5 HTTP basic authentication middleware. can you give an idea why this is coming like this?

**Comment by olsgreen** [comment]
What is the message it's giving? Is it 'Failed to boot Concrete5'?

**Comment by nmohanan** [comment]
No it is showing  "You have access to the Concrete5 API for the site named Array." this message, $siteName.$authString these two values are not getting

**Comment by olsgreen** [comment]
Which version of Concrete5 are you using? e.g. 5.x.x

**Comment by nmohanan** [comment]
Latest version 5.7.3.1

**Comment by olsgreen** [comment]
That would be why, this integration is for 5.6.x or lower. I haven't had a chance to look at getting it working with 5.7.x as of yet.

**Comment by nmohanan** [comment]
If possible can you help me, where i want to make changes and make this extension work with concrete latest version.

**Comment by nmohanan** [comment]
Please change the 'SITE' to concrete.site in the index.php, this will give the sitename

Thanks
